# Generated by Django 2.1.1 on 2019-11-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191130_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.FileField(default=None, upload_to=utils.upload.profile_image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile'),
            preserve_default=False,
        ),
    ]
