# Generated by Django 2.1.1 on 2019-11-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191130_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_ptr',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(default='Sedi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='image',
            field=models.FileField(default=None, upload_to=utils.upload.profile_image_path, validators=[utils.validators.image_size, utils.validators.image_extension]),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(default='Sedi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='business_center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bc_clients', to='main.BusinessCenter'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
