# Generated by Django 2.1.1 on 2019-11-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191130_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='business_center',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bc_clients', to='main.BusinessCenter'),
        ),
    ]
