# Generated by Django 2.1.1 on 2019-11-24 10:00

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_auto_20191124_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.FileField(default=None, upload_to=utils.upload.business_center_image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_business_centers', to='locations.Address')),
            ],
        ),
    ]
