# Generated by Django 2.1.1 on 2019-11-24 10:04

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscenter',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='businesscenter',
            name='image_url',
            field=models.FileField(default=None, null=True, upload_to=utils.upload.business_center_image_path, validators=[utils.validators.image_size, utils.validators.image_extension]),
        ),
    ]
