# Generated by Django 2.1.1 on 2019-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191124_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscenter',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
