# Generated by Django 2.1.1 on 2019-11-24 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20191124_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('image_url', models.FileField(default=None, null=True, upload_to=utils.upload.menu_image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField()),
                ('image_url', models.FileField(default=None, null=True, upload_to=utils.upload.menu_item_image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
                ('price', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_menu_items', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='main.Menu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
