# Generated by Django 2.1.1 on 2019-11-24 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_menu_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessCenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's business center",
                'verbose_name_plural': "User's business centers",
            },
        ),
        migrations.AlterUniqueTogether(
            name='businesscenteruser',
            unique_together={('business_center', 'user')},
        ),
    ]
