# Generated by Django 2.1.1 on 2019-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ordermenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='with_garnish',
            field=models.BooleanField(default=False),
        ),
    ]
