# Generated by Django 2.1.1 on 2019-11-30 15:55

from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191124_1000'),
        ('main', '0009_auto_20191125_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('image', models.FileField(default=None, null=True, upload_to=utils.upload.restaurant_image_path, validators=[utils.validators.image_size, utils.validators.image_extension])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_restaurants', to='locations.Address')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='businesscenteruser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='businesscenteruser',
            name='business_center',
        ),
        migrations.RemoveField(
            model_name='businesscenteruser',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessCenterUser',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='main.Restaurant'),
            preserve_default=False,
        ),
    ]
