# Generated by Django 2.1.1 on 2019-12-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191201_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenuitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu_items', to='main.Order'),
        ),
    ]
